package com.onemoreburh.mineswap.ui.theme

import androidx.compose.ui.graphics.Color

val PRIMARY_COLOR = Color(0xFFDDE5B6) //CREAM_COLOR
val SECONDARY_COLOR = Color(0xFF6C584C) //ASH_COLOR
val TEXT_COLOR = Color(0xFFF0EAD2)//VANILLA_CREAM_COLOR
val BORDER_COLOR = Color(0xFFADC178)//OLIVE_COLOR
val OPTIONAL_COLOR = Color(0xFFA98467)//COPPER_COLOR
val HIGHLIGHT_COLOR = Color(0xFFC65D3B)//TERRACOTTA_RED